### ISSUE TITLE
erreur de perm pour maj via panel

### ISSUE THREAD

**Issue by sadoj-kuro** [MineWeb/Plugin-FactionRanking#4]
Erreur : Le plugin ne peut pas être installé/mis à jour car le CMS ne dispose pas des droits d'écriture dans le dossier /app/Plugin/ (775 ou 755).

alors que le dossier a les perm et que pour le plugin forum sa a marcher

**Comment by Eywek** [comment]
yep en effet, y'a un problème avec les slugs de plugins mais ça correspond plus au CMS https://github.com/MineWeb/MineWebCMS/issues/35
